server:
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: console
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true:
        default_schema: public
#    hibernate:
#      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/tdm
    username: root
    password:
