server:
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/tdm
    username: root
    password:
